name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: senyaweb/fe
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod # Targets the 'prod' GitHub Environment for secrets and rules
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Removed Docker Metadata Action step

      - name: Build and push production image
        id: build-and-push
        env:
          ECR_REGISTRY_STEP_OUTPUT: ${{ steps.login-ecr.outputs.registry }}
        uses: docker/build-push-action@v5
        with:
          context: . # Assuming Dockerfile is at the root of Senya_web_FE_vue
          file: ./Dockerfile # Path to your frontend Dockerfile
          push: true
          tags: |
            ${{ env.ECR_REGISTRY_STEP_OUTPUT }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ env.ECR_REGISTRY_STEP_OUTPUT }}/${{ env.ECR_REPOSITORY }}:latest
          # labels: ${{ steps.meta.outputs.labels }} # Removed as docker/metadata-action is removed
          cache-from: type=gha,scope=prod
          cache-to: type=gha,scope=prod,mode=max

      - name: Print Image URI
        run: echo "Image pushed to ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"